In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
PROJECT_PATH = "/content/drive/MyDrive/gnn_bert_music_project"

FMA_PATH = PROJECT_PATH + "/datasets/fma"

MUSICCAPS_PATH = PROJECT_PATH + "/datasets/musiccaps"

PROCESSED_PATH = PROJECT_PATH + "/processed"

print(FMA_PATH)

/content/drive/MyDrive/gnn_bert_music_project/datasets/fma

In [ ]:
import os

for root, dirs, files in os.walk(FMA_PATH):
    level = root.replace(FMA_PATH,'').count(os.sep)

    if level < 2:
        print(root)
        for f in files[:5]:
            print("   ",f)

/content/drive/MyDrive/gnn_bert_music_project/datasets/fma
    fma_metadata.zip
    fma_medium.zip
/content/drive/MyDrive/gnn_bert_music_project/datasets/fma/fma_medium
/content/drive/MyDrive/gnn_bert_music_project/datasets/fma/fma_metadata

In [ ]:
import zipfile
import os

metadata_zip = FMA_PATH + "/fma_metadata.zip"

extract_path = FMA_PATH + "/fma_metadata"

with zipfile.ZipFile(metadata_zip,'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Metadata extracted")

Metadata extracted

In [ ]:
import pandas as pd

In [ ]:
tracks_file = (
    FMA_PATH +
    "/fma_metadata/fma_metadata/tracks.csv"
)

tracks = pd.read_csv(
    tracks_file,
    header=[0,1],
    index_col=0
)

tracks.head()

            album                                                     \
         comments         date_created        date_released engineer
track_id
2               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
3               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
5               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
10              0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN
20              0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN

                                                                          \
         favorites id                                information listens
track_id
2                4  1                                    <p></p>    6073
3                4  1                                    <p></p>    6073
5                4  1                                    <p></p>    6073
10               4  6                                        NaN   47632
20               2  4  <p> "spiritual songs" from Nicky Cook</p>    2710

                        ...       track                         \
         producer tags  ... information interest language_code
track_id                ...
2             NaN   []  ...         NaN     4656            en
3             NaN   []  ...         NaN     1470            en
5             NaN   []  ...         NaN     1933            en
10            NaN   []  ...         NaN    54881            en
20            NaN   []  ...         NaN      978            en

                                                                              \
                                                    license listens lyricist
track_id
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN
20        Attribution-NonCommercial-NoDerivatives (aka M...     361      NaN


         number publisher tags            title
track_id
2             3       NaN   []             Food
3             4       NaN   []     Electric Ave
5             6       NaN   []       This World
10            1       NaN   []          Freeway
20            3       NaN   []  Spiritual Level

[5 rows x 52 columns]

In [ ]:
tracks.shape

(106574, 52)

In [ ]:
audio_zip = FMA_PATH + "/fma_medium.zip"

audio_extract = FMA_PATH + "/fma_medium"

with zipfile.ZipFile(audio_zip,'r') as zip_ref:
    zip_ref.extractall(audio_extract)

print("Audio extracted")

Audio extracted

In [ ]:
!pip install librosa soundfile

Requirement already satisfied: librosa in /usr/local/lib/python3.13/dist-packages (0.11.0)
Requirement already satisfied: soundfile in /usr/local/lib/python3.13/dist-packages (0.14.0)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.13/dist-packages (from librosa) (3.1.0)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.13/dist-packages (from librosa) (0.61.2)
Requirement already satisfied: numpy>=1.22.3 in /usr/local/lib/python3.13/dist-packages (from librosa) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from librosa) (1.16.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from librosa) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.13/dist-packages (from librosa) (1.6.0)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.13/dist-packages (from librosa) (4.4.2)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.13/dist-packages (from librosa) (1.9.0)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.13/dist-packages (from librosa) (1.1.0)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.13/dist-packages (from librosa) (4.16.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.13/dist-packages (from librosa) (0.5)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.13/dist-packages (from librosa) (1.2.2)
Requirement already satisfied: standard-aifc in /usr/local/lib/python3.13/dist-packages (from librosa) (3.13.0)
Requirement already satisfied: standard-sunau in /usr/local/lib/python3.13/dist-packages (from librosa) (3.13.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.13/dist-packages (from soundfile) (2.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=1.0->soundfile) (3.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.0->librosa) (3.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from lazy_loader>=0.1->librosa) (26.3)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba>=0.51.0->librosa) (0.44.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from pooch>=1.1->librosa) (4.11.7)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.13/dist-packages (from pooch>=1.1->librosa) (2.32.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: standard-chunk in /usr/local/lib/python3.13/dist-packages (from standard-aifc->librosa) (3.13.0)
Requirement already satisfied: audioop-lts in /usr/local/lib/python3.13/dist-packages (from standard-aifc->librosa) (0.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.19.0->pooch>=1.1->librosa) (2026.7.22)

In [ ]:
import librosa

audio_path = (
    FMA_PATH+
    "/fma_medium/fma_medium/000/000002.mp3"
)

audio, sr = librosa.load(
    audio_path,
    sr=22050
)

print(audio.shape)
print(sr)

(660984,)
22050

In [ ]:
import os

PROJECT_PATH = "/content/drive/MyDrive/gnn_bert_music_project"

for item in os.listdir(PROJECT_PATH):
    print(item)

datasets
musiccaps
processed
models
results

In [ ]:
DATASET_PATH = PROJECT_PATH + "/datasets"

for item in os.listdir(DATASET_PATH):
    print(item)

fma
musiccaps

In [ ]:
import pandas as pd
import os

os.listdir(MUSICCAPS_PATH)

['musiccaps.csv']

In [ ]:
import pandas as pd

musiccaps_file = MUSICCAPS_PATH + "/musiccaps.csv"

musiccaps = pd.read_csv(musiccaps_file)

print(musiccaps.shape)
musiccaps.head()

(5521, 9)

,ytid,start_s,end_s,audioset_positive_labels,aspect_list,caption,author_id,is_balanced_subset,is_audioset_eval
0,-0Gj8-vB1q4,30,40,"/m/0140xf,/m/02cjck,/m/04rlf","['low quality', 'sustained strings melody', 's...",The low quality recording features a ballad so...,4,False,True
1,-0SdAVK79lg,30,40,"/m/0155w,/m/01lyv,/m/0342h,/m/042v_gx,/m/04rlf...","['guitar song', 'piano backing', 'simple percu...",This song features an electric guitar as the m...,0,False,False
2,-0vPFx-wRRI,30,40,"/m/025_jnm,/m/04rlf","['amateur recording', 'finger snipping', 'male...",a male voice is singing a melody with changing...,6,False,True
3,-0xzrMun0Rs,30,40,"/m/01g90h,/m/04rlf","['backing track', 'jazzy', 'digital drums', 'p...",This song contains digital drums playing a sim...,6,False,True
4,-1LrH01Ei1w,30,40,"/m/02p0sh1,/m/04rlf","['rubab instrument', 'repetitive melody on dif...",This song features a rubber instrument being p...,0,False,False

In [ ]:
musiccaps.columns

Index(['ytid', 'start_s', 'end_s', 'audioset_positive_labels', 'aspect_list',
       'caption', 'author_id', 'is_balanced_subset', 'is_audioset_eval'],
      dtype='object')

In [ ]:
musiccaps[['caption']].head(10)

                                             caption
0  The low quality recording features a ballad so...
1  This song features an electric guitar as the m...
2  a male voice is singing a melody with changing...
3  This song contains digital drums playing a sim...
4  This song features a rubber instrument being p...
5  This clip is three tracks playing consecutivel...
6  A male singer sings this groovy melody. The so...
7  someone is playing a high pitched melody on a ...
8  The Pop song features a soft female vocal sing...
9  low fidelity audio from a live performance fea...

In [ ]:
musiccaps.isnull().sum()

ytid                        0
start_s                     0
end_s                       0
audioset_positive_labels    0
aspect_list                 0
caption                     0
author_id                   0
is_balanced_subset          0
is_audioset_eval            0
dtype: int64

In [ ]:
musiccaps_clean = musiccaps.dropna()

musiccaps_clean.to_csv(
    PROJECT_PATH + "/processed/musiccaps_clean.csv",
    index=False
)

print("Saved:", musiccaps_clean.shape)

Saved: (5521, 9)

In [ ]:
musiccaps.shape
musiccaps.columns
musiccaps.head()

,ytid,start_s,end_s,audioset_positive_labels,aspect_list,caption,author_id,is_balanced_subset,is_audioset_eval
0,-0Gj8-vB1q4,30,40,"/m/0140xf,/m/02cjck,/m/04rlf","['low quality', 'sustained strings melody', 's...",The low quality recording features a ballad so...,4,False,True
1,-0SdAVK79lg,30,40,"/m/0155w,/m/01lyv,/m/0342h,/m/042v_gx,/m/04rlf...","['guitar song', 'piano backing', 'simple percu...",This song features an electric guitar as the m...,0,False,False
2,-0vPFx-wRRI,30,40,"/m/025_jnm,/m/04rlf","['amateur recording', 'finger snipping', 'male...",a male voice is singing a melody with changing...,6,False,True
3,-0xzrMun0Rs,30,40,"/m/01g90h,/m/04rlf","['backing track', 'jazzy', 'digital drums', 'p...",This song contains digital drums playing a sim...,6,False,True
4,-1LrH01Ei1w,30,40,"/m/02p0sh1,/m/04rlf","['rubab instrument', 'repetitive melody on dif...",This song features a rubber instrument being p...,0,False,False

In [ ]:
musiccaps.shape

(5521, 9)

In [ ]:
musiccaps.isnull().sum()

ytid                        0
start_s                     0
end_s                       0
audioset_positive_labels    0
aspect_list                 0
caption                     0
author_id                   0
is_balanced_subset          0
is_audioset_eval            0
dtype: int64

In [ ]:
musiccaps["caption_length"] = (
    musiccaps["caption"]
    .apply(lambda x: len(str(x).split()))
)

musiccaps["caption_length"].describe()

count    5521.000000
mean       48.968303
std        17.329780
min         3.000000
25%        37.000000
50%        46.000000
75%        60.000000
max       136.000000
Name: caption_length, dtype: float64

In [ ]:
for i in range(5):
    print("\nCaption", i+1)
    print(musiccaps.iloc[i]["caption"])

Caption 1
The low quality recording features a ballad song that contains sustained strings, mellow piano melody and soft female vocal singing over it. It sounds sad and soulful, like something you would hear at Sunday services.

Caption 2
This song features an electric guitar as the main instrument. The guitar plays a descending run in the beginning then plays an arpeggiated chord followed by a double stop hammer on to a higher note and a descending slide followed by a descending chord run. The percussion plays a simple beat using rim shots. The percussion plays in common time. The bass plays only one note on the first count of each bar. The piano plays backing chords. There are no voices in this song. The mood of this song is relaxing. This song can be played in a coffee shop.

Caption 3
a male voice is singing a melody with changing tempos while snipping his fingers rhythmically. The recording sounds like it has been recorded in an empty room. This song may be playing, practicing snipping and singing along.

Caption 4
This song contains digital drums playing a simple groove along with two guitars. One strumming chords along with the snare the other one playing a melody on top. An e-bass is playing the footnote while a piano is playing a major and minor chord progression. A trumpet is playing a loud melody alongside the guitar. All the instruments sound flat and are being played by a keyboard. There are little bongo hits in the background panned to the left side of the speakers. Apart from the music you can hear eating sounds and a stomach rumbling. This song may be playing for an advertisement.

Caption 5
This song features a rubber instrument being played. The strumming is fast. The melody is played on one fretted string and other open strings. The melody is played on the lower octave and is later repeated on the higher octave. This song can be played at a folk party.

In [ ]:
import os

os.listdir(FMA_PATH)

['fma_metadata.zip', 'fma_medium.zip', 'fma_medium', 'fma_metadata']

In [ ]:
for root, dirs, files in os.walk(FMA_PATH):
    print(root)
    print(files[:5])
    break

/content/drive/MyDrive/gnn_bert_music_project/datasets/fma
['fma_metadata.zip', 'fma_medium.zip']

In [ ]:
import os

print(os.listdir(FMA_PATH))

['fma_metadata.zip', 'fma_medium.zip', 'fma_medium', 'fma_metadata']

In [ ]:
for root, dirs, files in os.walk(FMA_PATH + "/fma_metadata"):
    print(root)
    print(files[:10])
    break

/content/drive/MyDrive/gnn_bert_music_project/datasets/fma/fma_metadata
[]

In [ ]:
import pandas as pd

tracks_path = (
    FMA_PATH +
    "/fma_metadata/fma_metadata/tracks.csv"
)

tracks = pd.read_csv(
    tracks_path,
    header=[0,1],
    index_col=0
)

tracks.head()

            album                                                     \
         comments         date_created        date_released engineer
track_id
2               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
3               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
5               0  2008-11-26 01:44:45  2009-01-05 00:00:00      NaN
10              0  2008-11-26 01:45:08  2008-02-06 00:00:00      NaN
20              0  2008-11-26 01:45:05  2009-01-06 00:00:00      NaN

                                                                          \
         favorites id                                information listens
track_id
2                4  1                                    <p></p>    6073
3                4  1                                    <p></p>    6073
5                4  1                                    <p></p>    6073
10               4  6                                        NaN   47632
20               2  4  <p> "spiritual songs" from Nicky Cook</p>    2710

                        ...       track                         \
         producer tags  ... information interest language_code
track_id                ...
2             NaN   []  ...         NaN     4656            en
3             NaN   []  ...         NaN     1470            en
5             NaN   []  ...         NaN     1933            en
10            NaN   []  ...         NaN    54881            en
20            NaN   []  ...         NaN      978            en

                                                                              \
                                                    license listens lyricist
track_id
2         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1293      NaN
3         Attribution-NonCommercial-ShareAlike 3.0 Inter...     514      NaN
5         Attribution-NonCommercial-ShareAlike 3.0 Inter...    1151      NaN
10        Attribution-NonCommercial-NoDerivatives (aka M...   50135      NaN
20        Attribution-NonCommercial-NoDerivatives (aka M...     361      NaN


         number publisher tags            title
track_id
2             3       NaN   []             Food
3             4       NaN   []     Electric Ave
5             6       NaN   []       This World
10            1       NaN   []          Freeway
20            3       NaN   []  Spiritual Level

[5 rows x 52 columns]

In [ ]:
tracks.shape

(106574, 52)

In [ ]:
medium_tracks = tracks[
    tracks[('set','subset')] == 'medium'
]

medium_tracks.shape

(17000, 52)

In [ ]:
medium_tracks[('track','genre_top')].value_counts()

(track, genre_top)
Rock                   6103
Electronic             5314
Experimental           1251
Hip-Hop                1201
Classical               619
Folk                    519
Old-Time / Historic     510
Jazz                    384
Instrumental            350
Pop                     186
Country                 178
Soul-RnB                154
Spoken                  118
Blues                    74
Easy Listening           21
International            18
Name: count, dtype: int64

In [ ]:
os.listdir(FMA_PATH)

['fma_metadata.zip', 'fma_medium.zip', 'fma_medium', 'fma_metadata']

In [ ]:
genre_counts = medium_tracks[
    ('track','genre_top')
].value_counts()

genre_counts

(track, genre_top)
Rock                   6103
Electronic             5314
Experimental           1251
Hip-Hop                1201
Classical               619
Folk                    519
Old-Time / Historic     510
Jazz                    384
Instrumental            350
Pop                     186
Country                 178
Soul-RnB                154
Spoken                  118
Blues                    74
Easy Listening           21
International            18
Name: count, dtype: int64

In [ ]:
fma_audio_path = FMA_PATH + "/fma_medium/fma_medium"

for root, dirs, files in os.walk(fma_audio_path):
    if len(files)>0:
        print(root)
        print(files[:5])
        break

/content/drive/MyDrive/gnn_bert_music_project/datasets/fma/fma_medium/fma_medium
['README.txt', 'checksums']

In [ ]:
!pip install librosa soundfile -q

In [ ]:
import librosa

sample_file = (
    fma_audio_path +
    "/000/000002.mp3"
)

audio, sr = librosa.load(
    sample_file,
    sr=22050
)

print("Sample rate:", sr)
print("Audio length:", len(audio))

Sample rate: 22050
Audio length: 660984